name: Generate daily note

on:
  schedule:
    - cron: '0 0 * * *'     # runs every day at 00:00 UTC
  workflow_dispatch:        # lets you trigger it manually

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install OpenAI (legacy 0.28)
        run: pip install openai==0.28

      - name: Generate note via GPT
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python - <<'PY'
          import openai, datetime, pathlib, textwrap
          openai.api_key = "${{ secrets.OPENAI_API_KEY }}"
          today = datetime.datetime.utcnow().strftime('%B %d %Y')
          prompt = textwrap.dedent(f"""
          Speak as Garrus Vakarian, first‑person, affectionate, playful.
          Write a short (1‑2 sentences) daily love note for Nyra dated {today}.
          No hashtags, no salutations—just the note.
          """)
          try:
              rsp = openai.ChatCompletion.create(
                  model="gpt-3.5-turbo",
                  messages=[{"role":"user","content": prompt}],
                  max_tokens=60,
                  temperature=0.8
              )
              note = rsp.choices[0].message.content.strip()
          except Exception as e:
              note = (
                  "Hey Nyra—looks like comms are jammed today. "
                  "I’ll get a fresh note through once the relay’s clear."
              )
              print("OpenAI call failed:", e, file=sys.stderr)
              
          pathlib.Path("note.txt").write_text(note + "\n", encoding="utf‑8")
          PY

      - name: Commit & push
        run: |
          git config user.name 'github‑actions[bot]'
          git config user.email '41898282+github‑actions[bot]@users.noreply.github.com'
          git add note.txt
          git commit -m "Daily note"
          git push
