name: Generate daily note

on:
  schedule:
    # 00:00 UTC  →  07:00 Asia/Jakarta
    - cron: '0 0 * * *'
  workflow_dispatch:      # manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣  Check out the repo
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2️⃣  Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # 3️⃣  Install latest OpenAI SDK
      - name: Install OpenAI
        run: pip install --quiet openai==1.*

      # 4️⃣  Generate note via GPT-4o-mini
      - name: Generate note via GPT
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python - <<'PY'
          import datetime, pathlib, textwrap, random
          from openai import OpenAI

          client = OpenAI()  # uses OPENAI_API_KEY env var

          today = datetime.datetime.now(datetime.UTC).strftime('%B %d %Y')

          prompt = textwrap.dedent(f"""
          You are Garrus Vakarian speaking in first person—affectionate, playful, wry, flirty sniper humor with a soft edge.
          Compose a DAILY love note for Nyra, 1-3 SHORT sentences.

          FORMAT RULES
          1. Put **each sentence** on its **own line**.
          2. After the final sentence, add a **flirty Turian signature** on a **new line** (examples below).
          3. No blank line after the signature.

          Signature examples (mix, vary, or improvise):
              – “–Your Archangel”
              – “–G”
              – “–Garrus, calibrating my heart”
              – “–Your favorite Turian sniper”
              – “–Archangel out”

          No hashtags, no salutations. Mention today’s date ({today}) only if it feels natural.
          Return **only** the formatted note, nothing else.
          """)

          try:
              rsp = client.chat.completions.create(
                model="gpt-4o-mini",
                messages=[{"role": "user", "content": prompt}],
                max_tokens=60,
                temperature=0.8
              )
              note = rsp.choices[0].message.content.strip()
          except Exception as e:
              print("OpenAI call failed:", e)
              backups = [
                "“Still thinking of you, Nyra.” \n –Garrus",
                "“Even without the comms, you’re all I can hear.” \n –Your Archangel",
                "“Calibrations paused; missing you isn’t.” \n –G",
                "“Turian systems offline, \n affection levels maxed.” \n –Garrus",
                "“I’m not good at poetry, \n but every shot I take spells ‘us’.” \n –Your Archangel",
                "“Out of ammo but never out of love.” \n –Your favorite sniper"
              ]
              note = random.choice(backups)

          pathlib.Path("note.txt").write_text(note, encoding="utf-8")
          PY

      # 5️⃣  Commit & push ONLY if note.txt changed
      - name: Commit & push if changed
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'

          if ! git diff --quiet note.txt; then
            echo "Changes detected—committing."
            git add note.txt
            git commit -m "Daily note"
            git push
          else
            echo "No changes in note.txt—skipping commit."
          fi
